### ISSUE TITLE
Contribute Request

### ISSUE THREAD

**Issue by TigerChenzzz** [GabeHasWon/StockableShops#2]
Hello GabeHasWon,
&emsp;I want to use this mod as a dependency of my mod, for that I want a shop with limited buy times, and I just happened to find this mod! But this mod does not meet my need, and I also have some issues with it:
- The goods' sell price is the same as the buy price. This is because the mod just set Item.buyOnce to true when add the good to a shop. Though this does achieve the functionality of stackable and consumable goods, but actually this item would be considered as sold to the shop by the player, and its sell price would be the same as the buy price, and mood's affection to the price is opposite to that of normal goods.
- An NPC might have multiple shops, but this mod seems not to consider this (though the dependents can handle this, it tends to be cumbersome).
- An NPC might not be a town NPC but could still have shops, but this mod just ignore it (e.g. Skeleton Merchant in vanilla).
- Shop stocks are not saved, and It is unable to save custom data for stocked shops (e.g. DryadStock in Verdant Mod need to save the day count (_dayCounter) (and also _dayCounter not reset when restocking, thould this should be a Verdant's Issue)).
- It is not possible to distinguish whether an item is stockable when it's stack is 1.
- ...

&emsp;So I think it would be great to just directly contribute to this mod! As long as you permit.
&emsp;I would greatly appreciate it if you could invite me as a collaborator of this repository! If you're concerned about this, I can also contribute through PRs, up to you.
&emsp;Looking forward to your reply.

---
(The above is translated from Chinese:)
您好!
&emsp;我希望将此模组作为我的模组的一个前置, 因为我需要有一个有限制购买次数的商店, 而我正好发现了这个模组! 但是这个模组并不能达到我的需求, 以及我发现此模组还有一些问题:
- 商店中物品的价格与卖出物品的价格相同, 这是因为在将物品添加入商店时只是将 Item.buyOnce 设置为了真, 虽然这样确实可以实现商品可堆叠可消耗的功能, 但实际上这个物品会被认为是由玩家卖出的物品, 其售价也会与回收价相同, 而且受心情影响与正常商品相反。
- 一个 NPC 可能会有多个商店, 但此模组似乎没有考虑这种情况 (虽然后置也能够处理, 但是会较为繁琐)。
- 一个 NPC 可能不是城镇 NPC (townNPC) 但仍然会有商店, 但此模组会忽略它 (原版就有骷髅商人的例子)。
- 商店中的物品数量不会被保存, 也无法保存自定义数据 (如 Verdant 中 DryadStock 的天数计数 (_dayCounter) (以及 _dayCounter 不会在刷新库存时重置, 虽说这条其实应该是 Verdant 的 Issue 就是了))。
- 当只有一个物品时无法区分是否是可堆叠的。
- ...

&emsp;因此我想不如直接给这个模组做贡献就好了, 只要您的允许。
&emsp;如果您能将我纳入此库的合作者中我会十分感激!  当然如果您不放心的话我也可以以 PR 的方式做贡献。
&emsp;期待您的回复。

**Comment by GabeHasWon** [comment]
（此消息是从原始英语机器翻译而来的。）
嗨！感谢您的见解。抱歉花了这么长时间，我一直在处理很多事情，很难跟踪。

1. 没有注意到。我为价格争论了很久，以至于我记不清我为什么要设置 buyOnce；周末我可以研究一下。如果事情很简单，就是不这样做，那肯定会在下周完成。
2. 我没有处理过很多极端情况，我从来没有需要考虑或在我的项目中使用多个商店。这是低优先级，但我确信我可以找到解决办法。
3. 坦率地说，我认为这已经可以工作了。不是吗？没有测试它，因为我没有想到它。
4. 我绝对可以在 StockableShop 中为 Save/LoadData 创建一个钩子，就像许多 tMod 类一样。这是一个非常常见的用例，我绝对可以更好地解释。 （感谢 Verdant 的报告，哈哈）
5. 不确定这是什么意思。
就我个人而言，我更喜欢 PR，因为我想仔细检查并确保你的所有贡献都是好的和一致的。如果你 PR 的内容足够一致，我会非常高兴让你成为贡献者。

---

Hi! Thanks for your insight. Sorry for taking so long, I've been working on so many things it's hard to keep track.

1. Didn't notice that. I've fought so much with the prices that I don't remember exactly why I set buyOnce; I can look into that come the weekend. If it's as simple as not doing that, that's definitely going to be done by next week.
2. I haven't played with many edge cases, and I haven't ever needed to consider or use multiple shops within my projects.  This is low priority but I'm sure I could find a fix for this.
3. Frankly, I thought this would work already. Does it not? Didn't test it, as I didn't think of it.
4. I could definitely make a hook for Save/LoadData, like a lot of tMod classes, in StockableShop. This is a very common use case that I could definitely account for better. (and thanks for the Verdant report lol)
5. Not sure what this means.

Personally I'd be more comfortable with PRs, as I'd want to double check and make sure all of your contributions are good and consistent anyway. If you PR enough consistent stuff, I'd be more than happy to have you on as a contributor.

**Comment by TigerChenzzz** [comment]
OK
